// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _11___EntityFrameworkEX.Data;

namespace _11___EntityFrameworkEX.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211020154835_moveasdwq")]
    partial class moveasdwq
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("_11___EntityFrameworkEX.Models.Moves", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<int>("SuperheroID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuperheroID");

                    b.ToTable("Moveset");
                });

            modelBuilder.Entity("_11___EntityFrameworkEX.Models.SuperHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CanFly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SuperHeroes");
                });

            modelBuilder.Entity("_11___EntityFrameworkEX.Models.Moves", b =>
                {
                    b.HasOne("_11___EntityFrameworkEX.Models.SuperHero", null)
                        .WithMany("Moveset")
                        .HasForeignKey("SuperheroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_11___EntityFrameworkEX.Models.SuperHero", b =>
                {
                    b.Navigation("Moveset");
                });
#pragma warning restore 612, 618
        }
    }
}
